version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: meuusuario
      MONGO_INITDB_ROOT_PASSWORD: minhasenha
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: